key:
  SERVICE_ACCOUNT_FILE: D:\Practice\Firebase\serviceAccount.json
  DATABASE_URL: https://stayhelp-v1.firebaseio.com
  ORDER_EXCEL_FILE: D:\Practice\Firebase\Input order file.xlsx
  MAIL_FROM: atultingre.test@gmail.com
  MAIL_PASS: Amazon@1122

spring:  profiles:    active: dev  application:    name: AmazonShippingApplication
---
spring:  profiles: devserver:  port: 7777
  
---
spring:
  profiles: prod
server:
  port: 8888
  

---
logging:  file:    name: AplicationBackend.log
  pattern:    file: "%d %p %c{1.} [%t] %m%n"
    console: "%d{HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"